### ISSUE TITLE
Merge consecutive whitespace

### ISSUE THREAD

**Issue by LeopoldArkham** [LeopoldArkham/Molten#21]
Currently the parser ends whitespace whenever a newline is reached. When appending a WS item, check that it does not follow another WS item,and merge them together if it does.

Look for the `todo` in `parse_item()`, currently on line 135.

**Comment by jeremydavis519** [comment]
I'd like to take this one if you don't mind. I should have a working version soon. But just to be clear, when you refer to a "WS item," that means a line that contains nothing but whitespace, right? Nothing else seems to make sense, given the source code that I've read since discovering this project a few hours ago. (In particular, I thought at first that any whitespace surrounding a newline would count, but that's clearly not right.)

**Comment by LeopoldArkham** [comment]
Hey, great to have you!

Yes. I do specifically mean [`Item::WS`](https://github.com/LeopoldArkham/Molten/blob/7305272a90d56f7e7a92f4a1c69354ae758e9aa0/src/items.rs#L153) elements should be concatenated into a single one if multiple of them occur  consecutively.

Couple things I didn't mention in the OP:
- Ideally this would stay allocation-free. Meaning you can keep track of the start index of the last WS element and create a new slice if another WS element follow it. You could also go unsafe and use [`slice::from_raw_parts](https://doc.rust-lang.org/core/slice/fn.from_raw_parts.html) if you feel like it.
- Ideally this would happen as the items are parsed, not as a second pass
- There should be a test for it, but it doesn't need to be in the first draft of the PR.

Let me know if you need anything!
